### ISSUE TITLE
Set `Scope=link` on ipv4 routing entries

### ISSUE THREAD

**Issue by flu0r1ne** [flu0r1ne/wg2nd#5]
> ipv4 routing entries should probably have Scope=link set.

Contributed by @itoffshore on [aurweb](https://aur.archlinux.org/packages/wg2nd)

**Comment by flu0r1ne** [comment]
Either `networkd` or the kernel seems to set the scope to `link` on my machine, both for IPv4 and IPv6 routes. Here are some examples:

```
ip route show table 2088138254
default dev remote-net proto static scope link
``` 

```
ip route show main
192.168.112.0 dev flu0r1ne-net proto static scope link
192.168.112.0/30 dev flu0r1ne-net proto kernel scope link src 192.168.112.1
```

`wg-quick` doesn't seem to manually specify the scope. If the scope set by `wg-quick` and the `networkd` configuration do not match, please let me know and I will look into it further.

**Comment by itoffshore** [comment]
ok - it must be a default setting nowadays by `networkd` (previously the Arch wiki showed it as being needed)

I mentioned it after looking back at my old `systemd-networkd` config files

checking my route table `wg-quick` also sets the scope as `link` (so this issue can probably be closed)

**Comment by flu0r1ne** [comment]
Great. Thanks.
