### ISSUE TITLE
Support CRLF in config files

### ISSUE THREAD

**Issue by dacioromero** [flu0r1ne/wg2nd#6]
This tool is incredibly useful, but it currently doesn't work with files that use CRLF instead of LF for newlines. AirVPN generates their configs as CRLF.

When trying a config file with CRLF the following error is outputed:

`"arsing error (line 1): Expected key-value pair, got "[Interface`

**Comment by flu0r1ne** [comment]
Interesting. I figured only Unix-style line feeds would be used. I updated the source and cut a new release to fix this issue. ( See v0.2.1) Feel free to reopen this issue if you have additional questions or comments.
